# Generated by Django 4.2.2 on 2023-07-09 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_card_artist_card_cardtype_card_colors_card_manacost_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='card',
            old_name='cardType',
            new_name='types',
        ),
        migrations.AddField(
            model_name='card',
            name='manaValue',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='card',
            name='manaCost',
            field=models.CharField(max_length=65),
        ),
    ]
