# Generated by Django 4.2.2 on 2023-07-23 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_card_copies'),
    ]

    operations = [
        migrations.CreateModel(
            name='collection_table_entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
