# Generated by Django 4.2.2 on 2023-07-23 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_collection_table_entry'),
    ]

    operations = [
        migrations.CreateModel(
            name='collections_manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='collection_table_entry',
            name='count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collection_table_entry',
            name='setcode',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
    ]
