# Generated by Django 4.2.2 on 2023-07-24 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_collections_manager_collection_table_entry_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection_table_entry',
            name='percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collection_table_entry',
            name='total',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
