# Generated by Django 4.2.2 on 2023-07-24 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_remove_collection_table_entry_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection_table_entry',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
