# Generated by Django 4.2.2 on 2023-07-24 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_collection_table_entry_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection_table_entry',
            name='ratio',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
    ]
