# Generated by Django 4.2.2 on 2023-08-07 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_set_tracker_set_tracker_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='set_tracker',
            name='unique',
            field=models.IntegerField(default=0),
        ),
    ]
